# Site settings
title: Clean Blog
header-img: img/wood-lot.jpg
email: casey@manion.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "https://github.com/caseman72"
twitter_username: caseman72
github_username:  caseman72
facebook_username:  idesofmarch72

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
